HR_WebApp/Models/ErrorViewModel.cs
namespace HR_WebApp.Models
{
    public class ErrorViewModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

HR_WebApp/Models/StaffCreateViewModel.cs
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;


namespace HR_WebApp.Models
{
    public class StaffCreateViewModel
    {
        [DisplayName("Voornaam")]
        [Required, MaxLength(50)]
        public string FirstName { get; set; }
        [DisplayName("Achternaam")]
        [Required, MaxLength(50)]
        public string LastName { get; set; }
        [DisplayName("Adres")]
        [MaxLength(100)]
        public string Address { get; set; }
        [DisplayName("Tewerkstelling sinds")]
        [Required]
        public DateOnly DOE { get; set; }

    }
}

HR_WebApp/Models/StaffListViewModel.cs
namespace HR_WebApp.Models
{
    public class StaffListViewModel
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public DateOnly DOE { get; set; }
    }
}

HR_WebApp/Controllers/HomeController.cs
using HR_WebApp.Models;
using Microsoft.AspNetCore.Mvc;
using System.Diagnostics;

namespace HR_WebApp.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

HR_WebApp/Controllers/StaffController.cs
using HR_WebApp.Database;
using HR_WebApp.Models;
using Microsoft.AspNetCore.Mvc;

namespace HR_WebApp.Controllers
{
    public class StaffController : Controller
    {
        private readonly IStaffDatabase staffDatabase;

        public StaffController(IStaffDatabase staffDatabase)
        {
            this.staffDatabase = staffDatabase;
        }

        public IActionResult Overview()
        {
            var vm = staffDatabase.GetAll().Select(x => new StaffListViewModel
            {
                Id = x.Id,  // <-- nodig voor selectie
                FirstName = x.FirstName,
                LastName = x.LastName,
                DOE = x.DOE, // <-- nodig voor sorteren
            } );
            
            return View(vm);
        }


        public IActionResult Create()
        {
            return View();
        }
    }
}

HR_WebApp/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

HR_WebApp/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - HR_WebApp</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/HR_WebApp.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">HR_WebApp</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Staff" asp-action="Overview">Personeelsleden</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - HR_WebApp - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>

HR_WebApp/Views/Staff/Create.cshtml
@model StaffCreateViewModel

<form>
    <div asp-controller="Staff" asp-action="Create" method="post">
        <label asp-for="FirstName"></label>
        <input asp-for="FirstName" class="form-control" />
        <span asp-validation-for="FirstName" class="text-info"></span>

        <label asp-for="LastName"></label>
        <input asp-for="LastName" class="form-control" />
        <span asp-validation-for="LastName" class="text-info"></span>

        <label asp-for="Address"></label>
        <input asp-for="Address" class="form-control" />
        <span asp-validation-for="Address" class="text-info"></span>

        <label asp-for="DOE"></label>
        <input asp-for="DOE" class="form-control" />
        <span asp-validation-for="DOE" class="text-info"></span>
    </div>

    <button class="btn btn-primary" type="submit">Toevoegen</button>
</form>

HR_WebApp/Views/Staff/Overview.cshtml
@model IEnumerable<StaffListViewModel>;

    <h1>Staff</h1>

    <a asp-controller="Staff" asp-action="Ĉreate">Personeelslid toevoegen</a>

    <table>
        <thead>
            <tr>
                <th>Voornaam</th>
                <th>Achternaam</th>
            </tr>
        </thead>
        <tbody>
            @foreach (var item in Model)
            {
                <tr>
                    <td>@item.FirstName</td>
                    <td>@item.LastName</td>
                </tr>
            }
        </tbody>
    </table>